platform :ios, '13.0'

def commonTestsPods
  pod 'Quick'
  pod 'Nimble'
  pod 'Mocker'
  pod 'SnapshotTesting'
end

target 'VieSureAssignment' do
  use_frameworks!

  pod 'SwiftFormat/CLI'

  target 'VieSureAssignmentTests' do
    inherit! :search_paths
    
    commonTestsPods
  end

  target 'VieSureAssignmentUITests' do
    commonTestsPods
  end

  target 'UtilsTests' do
    inherit! :search_paths

    commonTestsPods
  end

  target 'ArticleListTests' do
    inherit! :search_paths

    commonTestsPods
  end

  target 'ArticleDetailsTests' do
    inherit! :search_paths

    commonTestsPods
  end

  target 'DesignSystemTests' do
    inherit! :search_paths

    commonTestsPods
  end
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
    end
end
